import { useRecommendations } from '@/hooks/useRecommendations'
import { Card } from '@/components/ui/Card'

export function RecommendationsPage() {
  const { data, isLoading, error } = useRecommendations()

  if (isLoading) return <p className="text-sm text-ink-muted">Loading…</p>
  if (error) return <p className="text-sm text-cat-6">Failed to load recommendations.</p>

  return (
    <div className="flex flex-col gap-4">
      <h1 className="text-lg font-semibold text-ink">Monthly Recommendations</h1>
      {!data ? (
        <p className="text-sm text-ink-muted">
          No recommendations yet — these are generated by the monthly analysis job.
        </p>
      ) : (
        <Card>
          <div className="whitespace-pre-wrap text-sm leading-relaxed text-ink-secondary">
            {data.suggestions}
          </div>
        </Card>
      )}
    </div>
  )
}
